[package]
name = "day1"
edition.workspace = true
version.workspace = true
authors.workspace = true
description.workspace = true

[dependencies]
utils = { path = "../utils" }
tokio = { workspace = true }
