[workspace]
resolver = "2"
members = [ "day1","utils"]

[workspace.package]
edition = "2021"
version = "0.1.0"
authors = ["matzxrr"]
description = "Advent of Code 2024 solution"

[workspace.dependencies]
nom = "7.1.3"
reqwest = "0.12.9"
tokio = { version = "1.4.1", features = ["full"] }

